apiVersion: v1
kind: Service
metadata:
  name: nodeport-gra-service
spec:
  type: NodePort
  selector:
    release: prometheus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000
