apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    release: prometheus 
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    release: prometheus
  type: LoadBalancer
