apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
  labels:
    app: django-app
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: django-app
  type: LoadBalancer
